# Generated by Django 3.0.4 on 2020-03-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200305_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observer',
            old_name='user',
            new_name='observer',
        ),
    ]
