# Generated by Django 3.0.4 on 2020-03-07 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20200307_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Log',
        ),
    ]
