# Generated by Django 3.0.4 on 2020-03-07 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20200307_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='habit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.Habit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
