# Generated by Django 3.0.4 on 2020-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200307_0133'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='observer',
            constraint=models.UniqueConstraint(fields=('observer', 'habit'), name='unique_observers'),
        ),
    ]
